import Config

# Override base URL for development
config :trivia_advisor,
  base_url: "http://localhost:4003"

# =============================================================================
# Database Configuration for Development
# =============================================================================
#
# Since Trivia Advisor is completely read-only, we connect directly to the
# production PlanetScale database in dev mode. This makes development testing
# much more realistic and eliminates the need for a local database setup.
#
# Required environment variables (in .env file):
#   PLANETSCALE_DATABASE_HOST
#   PLANETSCALE_DATABASE
#   PLANETSCALE_DATABASE_USERNAME
#   PLANETSCALE_DATABASE_PASSWORD
#
# Note: Your IP must be allowed in PlanetScale's access controls.

# Load environment from .env file for development
if File.exists?(".env") do
  for line <- File.read!(".env") |> String.split("\n"),
      line != "",
      not String.starts_with?(line, "#") do
    case String.split(line, "=", parts: 2) do
      [key, value] -> System.put_env(String.trim(key), String.trim(value))
      _ -> :ok  # Skip malformed lines
    end
  end
end

ps_host = System.get_env("PLANETSCALE_DATABASE_HOST") || "localhost"
ps_db = System.get_env("PLANETSCALE_DATABASE") || "eventasaurus_dev"
ps_user = System.get_env("PLANETSCALE_DATABASE_USERNAME") || "postgres"
ps_pass = System.get_env("PLANETSCALE_DATABASE_PASSWORD") || "postgres"
ps_port = String.to_integer(System.get_env("PLANETSCALE_PG_BOUNCER_PORT") || "6432")

# SSL configuration for PlanetScale (when using remote database)
# Note: CAStore.file_path() isn't available at config time, so we use
# the system CA bundle path directly for dev mode
ssl_config =
  if ps_host != "localhost" do
    # Use system CA bundle on macOS
    cacert_path =
      cond do
        File.exists?("/etc/ssl/cert.pem") -> "/etc/ssl/cert.pem"
        File.exists?("/etc/ssl/certs/ca-certificates.crt") -> "/etc/ssl/certs/ca-certificates.crt"
        true -> nil
      end

    if cacert_path do
      [
        ssl: true,
        ssl_opts: [
          verify: :verify_peer,
          cacertfile: cacert_path,
          server_name_indication: String.to_charlist(ps_host),
          customize_hostname_check: [
            match_fun: :public_key.pkix_verify_hostname_match_fun(:https)
          ]
        ]
      ]
    else
      # Fallback: SSL without strict verification (dev only)
      [ssl: true, ssl_opts: [verify: :verify_none]]
    end
  else
    []
  end

config :trivia_advisor, TriviaAdvisor.Repo,
  [
    username: ps_user,
    password: ps_pass,
    hostname: ps_host,
    port: ps_port,
    database: ps_db,
    pool_size: 5,
    timeout: 30_000,
    queue_target: 5_000,
    queue_interval: 1_000,
    show_sensitive_data_on_connection_error: true,
    # Disable prepared statements for PgBouncer compatibility
    prepare: :unnamed
  ] ++ ssl_config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :trivia_advisor, TriviaAdvisorWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4003")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "kSCQyP7VzHXdmQ066mSJMVmllzkQCKhflrIpnB2yEXrSfh3akH3saL1d4tSQQgFA",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:trivia_advisor, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:trivia_advisor, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :trivia_advisor, TriviaAdvisorWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/trivia_advisor_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :trivia_advisor, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
